### ISSUE TITLE
Players losing items without dropping them on death on quilt

### ISSUE THREAD

**Issue by CephalonCosmic** [TeamTwilight/twilightforest-fabric#135]
### Fabric Loader Version

Quilt Loader 0,17,6

### Fabric API Version

Quilted Fabric API 4.0.0-beta.19+0.64.0-1.19.2

### Twilight Forest Version

4.2.301

### Client Log

https://gist.github.com/CephalonCosmic/912f4fb8cbd7ce16b204df57dccf8e1f

### Steps to Reproduce

1. Create an instance with Quilt 0.17.6
2. Install the mods
- Cloth Config 8.2.88
- Porting Lib 2.0.605+1.19.2
- Quilted Fabric API 4.0.0-beta.19+0.64.0-1.19.2
- Twilight Forest Fabric 4.2.301
- You're in Grave Danger 1.4.5
3. Start the game, create a world, collect items
4. Die somehow

### What You Expected

A grave with my items to appear and the message in chat to tell me the graves location.

### What Happened Instead

Nothing. no grave, no items. everything is voided.

### Additional Details

Video of the steps to reproduce this.
https://cdn.discordapp.com/attachments/1000973473541263420/1040210635369218058/2022-11-10_23-21-39.mp4

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by CephalonCosmic** [comment]
I have also tried this on Fabric Loader and nothing happened, this is a Quilt exclusive issue.

**Comment by CyberSteve777** [comment]
I can confirm that this issue can be reproduced only with Twilight forest & its dependencies. I have made a fresh installation on quilt with TF, dependencies and regular optimisation mods (sodium + indium, lithium and so on) and did /kill command with items in inventory. After applying command I saw that regular dark red screen with "You died", but when I looked at hotbar I saw that items were still here. And when I pressed "Respawn" button, all items in inventory dissapeared, without dropping on ground.

**Comment by CyberSteve777** [comment]
Here goes my reproduction of issue:
https://drive.google.com/file/d/1OJp18lP6ppc3_VhahVJ7tIc6T8ru6iJz/view?usp=share_link

**Comment by CyberSteve777** [comment]
@CephalonCosmic could you change title pls

**Comment by CephalonCosmic** [comment]
@CyberSteve777 Change it to what exactly?

**Comment by CyberSteve777** [comment]
> @CyberSteve777 Change it to what exactly?

Player losing items without dropping them on death on quilt

**Comment by CephalonCosmic** [comment]
Oh I see, this is so much worse

> Here goes my reproduction of issue: https://drive.google.com/file/d/1OJp18lP6ppc3_VhahVJ7tIc6T8ru6iJz/view?usp=share_link

**Comment by CyberSteve777** [comment]
the issue still persists on 4.2.310 of Twilight Forest though

**Comment by mchopkins9** [comment]
The issue persists with TF 4.2.310 and the latest version of YIGD. It is also an issue with Universal Graves. Proper death messages are also not appearing in chat or logs.

**Comment by TropheusJ** [comment]
seems fixed. tested alone, with YIGD, and with Gravestones.

**Comment by mchopkins9** [comment]
Which versions of quilt and the mods did you use?

**Comment by TropheusJ** [comment]
It’s fixed in dev builds, not released yet.

**Comment by CyberSteve777** [comment]
Sadly, my issue still persists in 4.2.312 version of TF

**Comment by GizmoTheMoonPig** [comment]
did you not read what tropheus wrote above, its not released yet

**Comment by Tamaized** [comment]
> did you not read what tropheus wrote above, its not released yet

4.2.312 is the current dev build, so it's still broken according to this user.

**Comment by TropheusJ** [comment]
oops, I forgot to switch out FAPI for QFAPI. debugging more.

**Comment by TropheusJ** [comment]
Tracked it down, QFAPI's event is incorrect, and cancellation is inverted. Needs to be fixed by them.
https://github.com/QuiltMC/quilted-fabric-api/issues/50

**Comment by mchopkins9** [comment]
Thank you so much for your help 👍

**Comment by someone5678** [comment]
I can confirm this issue is fixed with latest TF dev build 4.2.312 and this QFAPI PR(not merged yet):
https://github.com/QuiltMC/quilted-fabric-api/pull/51

Github action build:
https://github.com/QuiltMC/quilted-fabric-api/actions/runs/3627526649

**Comment by CyberSteve777** [comment]
QFAPI updated, and my part of issue is no longer producable. I think the issue is now fixed fully and can be closed

**Comment by TropheusJ** [comment]
QFAPI 4.0.0-beta.24 fixes this
